[package]
name = "llm-bot-skills"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
llm-bot-core.workspace = true
globset.workspace = true
humantime-serde.workspace = true
serde.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
