//! The texts the bot posts to a PR. Platform-independent markdown.

use momulus_core::{Finding, JobId};

use crate::validate::ReviewResult;

/// Shared context for the signature under a message.
#[derive(Debug, Clone)]
pub struct JobContext<'a> {
    pub job_id: JobId,
    pub skill: &'a str,
    /// The command exactly as a human wrote it.
    pub command: &'a str,
}

impl JobContext<'_> {
    /// Signature: it is how the job's logs are found.
    fn footer(&self) -> String {
        format!(
            "\n<sub>skill `{}` · job `{}`</sub>\n",
            self.skill,
            self.job_id.short()
        )
    }
}

/// Review body: the model's summary plus whatever did not fit into inline comments.
pub fn review_summary(result: &ReviewResult, ctx: &JobContext<'_>, files: usize) -> String {
    let mut out = format!(
        "**`{}`** — files checked: {}, findings: {}.\n\n",
        ctx.command,
        files,
        result.inline.len() + result.out_of_diff.len() + result.unknown_path.len()
    );

    if !result.summary.trim().is_empty() {
        out.push_str(result.summary.trim());
        out.push_str("\n\n");
    }

    if !result.out_of_diff.is_empty() {
        out.push_str(&format!(
            "**Outside the changed lines ({})** — these cannot be anchored to a line, so they are listed here:\n\n",
            result.out_of_diff.len()
        ));
        out.push_str(&finding_list(&result.out_of_diff));
        out.push('\n');
    }

    if !result.unknown_path.is_empty() {
        out.push_str(&format!(
            "**About files outside the skill's scope ({})**:\n\n",
            result.unknown_path.len()
        ));
        out.push_str(&finding_list(&result.unknown_path));
        out.push('\n');
    }

    if result.truncated > 0 {
        out.push_str(&format!(
            "{} more findings are not shown: the comment limit kicked in.\n\n",
            result.truncated
        ));
    }

    if result.is_empty() {
        out.push_str("No findings.\n\n");
    }

    out.push_str(&ctx.footer());
    out
}

/// Renders findings as a markdown list.
fn finding_list(findings: &[Finding]) -> String {
    let mut out = String::new();
    for finding in findings {
        let place = if finding.line == 0 {
            finding.path.clone()
        } else {
            format!("{}:{}", finding.path, finding.line)
        };
        out.push_str(&format!(
            "- `{place}` _{}_ — {}\n",
            finding.severity.as_str(),
            finding.body.trim()
        ));
    }
    out
}

/// Title of the pull request carrying the changes.
pub fn pr_title(
    skill: &str,
    source_pr: u64,
    args: &std::collections::BTreeMap<String, String>,
) -> String {
    let suffix = if args.is_empty() {
        String::new()
    } else {
        let joined = args
            .iter()
            .map(|(k, v)| format!("{k}={v}"))
            .collect::<Vec<_>>()
            .join(", ");
        format!(" ({joined})")
    };
    format!("momulus: {skill}{suffix} for #{source_pr}")
}

/// Body of the pull request carrying the changes.
pub fn pr_body(
    ctx: &JobContext<'_>,
    source_pr: u64,
    summary: Option<&str>,
    files: &[String],
) -> String {
    let mut out = format!(
        "Generated by the command `{}` in #{source_pr}.\n\n",
        ctx.command
    );

    match summary.map(str::trim).filter(|s| !s.is_empty()) {
        Some(summary) => {
            out.push_str(summary);
            out.push_str("\n\n");
        }
        None => out.push_str("The skill left no summary.\n\n"),
    }

    out.push_str(&format!("**Changed files ({})**:\n\n", files.len()));
    for file in files {
        out.push_str(&format!("- `{file}`\n"));
    }
    out.push('\n');
    out.push_str(&ctx.footer());
    out
}

/// Reply for a command that has nothing to do.
pub fn nothing_to_do(ctx: &JobContext<'_>, filters: &[String]) -> String {
    let filters = if filters.is_empty() {
        "the whole repository".to_string()
    } else {
        filters
            .iter()
            .map(|f| format!("`{f}`"))
            .collect::<Vec<_>>()
            .join(", ")
    };
    format!(
        "Nothing to do: none of the files changed in this PR match the skill filter ({filters}).\n{}",
        ctx.footer()
    )
}

/// Reply for a patch skill that changed nothing.
pub fn no_changes(ctx: &JobContext<'_>, summary: Option<&str>) -> String {
    let mut out = String::from("The skill ran, but no files were changed.\n\n");
    if let Some(summary) = summary.map(str::trim).filter(|s| !s.is_empty()) {
        out.push_str(summary);
        out.push_str("\n\n");
    }
    out.push_str(&ctx.footer());
    out
}

/// Error message: no stack traces and no secrets.
pub fn error_comment(ctx: &JobContext<'_>, reason: &str) -> String {
    format!(
        "The command `{}` did not run: {}\n{}",
        ctx.command,
        reason.trim(),
        ctx.footer()
    )
}

/// Reply for a command that could not be parsed.
pub fn help_comment(reason: &str, registry_help: &str) -> String {
    format!(
        "I could not parse that command: {}\n\n{}",
        reason.trim(),
        registry_help.trim_end()
    )
}

/// Reply for an input that is too large.
pub fn too_large(ctx: &JobContext<'_>, reason: &str) -> String {
    format!(
        "The command `{}` did not run: {}\nNarrow the PR down or tighten the skill's file filter.\n{}",
        ctx.command,
        reason.trim(),
        ctx.footer()
    )
}

/// Reply for a patch command on a PR from a fork.
pub fn fork_unsupported(ctx: &JobContext<'_>, head_repo: &str) -> String {
    format!(
        "The command `{}` did not run: this PR comes from the fork `{head_repo}`, \
         and the bot has no write access there. Patch-mode skills only work on \
         branches of the main repository.\n{}",
        ctx.command,
        ctx.footer()
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use momulus_core::{Severity, Uuid};
    use std::collections::BTreeMap;

    /// A fixed id so the snapshots stay stable.
    fn ctx<'a>(command: &'a str, skill: &'a str) -> JobContext<'a> {
        JobContext {
            job_id: JobId(Uuid::from_u128(0x1a2b3c4d_5e6f_7081_9202_a3b4c5d6e7f8)),
            skill,
            command,
        }
    }

    fn finding(path: &str, line: u32, severity: Severity, body: &str) -> Finding {
        Finding {
            path: path.to_string(),
            line,
            severity,
            body: body.to_string(),
            suggestion: None,
        }
    }

    #[test]
    fn review_summary_snapshot() {
        let result = ReviewResult {
            summary: "The post has plenty of punctuation problems and inconsistent\nspelling of acronym-based terms.".into(),
            inline: vec![
                finding("posts/dns.md", 18, Severity::Typo, "Repetition: \"a nice nice domain\""),
                finding("posts/dns.md", 178, Severity::Typo, "\"requred\" → \"required\""),
            ],
            out_of_diff: vec![finding(
                "posts/dns.md",
                420,
                Severity::Terminology,
                "«MacOS» → «macOS»",
            )],
            unknown_path: vec![finding(
                "astro.config.ts",
                10,
                Severity::Other,
                "This file is outside the skill's scope",
            )],
            truncated: 5,
        };
        insta::assert_snapshot!(
            "review_summary",
            review_summary(&result, &ctx("/llm proofread", "proofread"), 2)
        );
    }

    #[test]
    fn empty_review_summary_snapshot() {
        let result = ReviewResult {
            summary: "All clean, nothing to report.".into(),
            ..Default::default()
        };
        insta::assert_snapshot!(
            "review_summary_empty",
            review_summary(&result, &ctx("/llm proofread", "proofread"), 1)
        );
    }

    #[test]
    fn pr_body_snapshot() {
        let files = vec![
            "content/posts/dns/index.en.md".to_string(),
            "content/posts/act/index.en.md".to_string(),
        ];
        insta::assert_snapshot!(
            "pr_body",
            pr_body(
                &ctx("/llm translate en", "translate"),
                42,
                Some("Translated two posts; terminology and code blocks were left as is."),
                &files
            )
        );
    }

    #[test]
    fn pr_title_includes_args() {
        let args = BTreeMap::from([("lang".to_string(), "en".to_string())]);
        assert_eq!(
            pr_title("translate", 42, &args),
            "momulus: translate (lang=en) for #42"
        );
        assert_eq!(
            pr_title("translate", 42, &BTreeMap::new()),
            "momulus: translate for #42"
        );
    }

    #[test]
    fn service_messages_snapshot() {
        let ctx = ctx("/llm proofread", "proofread");
        let mut out = String::new();
        out.push_str("=== nothing to do ===\n");
        out.push_str(&nothing_to_do(
            &ctx,
            &["**/*.md".to_string(), "**/*.mdx".to_string()],
        ));
        out.push_str("\n=== no changes ===\n");
        out.push_str(&no_changes(&ctx, Some("Everything is already translated.")));
        out.push_str("\n=== error ===\n");
        out.push_str(&error_comment(
            &ctx,
            "the model returned invalid JSON twice",
        ));
        out.push_str("\n=== too large ===\n");
        out.push_str(&too_large(
            &ctx,
            "the PR diff is 812 KB against a 400 KB limit",
        ));
        out.push_str("\n=== fork ===\n");
        out.push_str(&fork_unsupported(&ctx, "contributor/blojik"));
        insta::assert_snapshot!("service_messages", out);
    }

    #[test]
    fn help_comment_snapshot() {
        insta::assert_snapshot!(
            "help_comment",
            help_comment(
                "unknown skill \"proofraed\"",
                "Available commands:\n\n- `/llm proofread` (review) — proofreading\n- `/llm translate <lang>` (patch) — translation\n\nFormat: `/llm <skill> [arguments]`.\n"
            )
        );
    }

    #[test]
    fn error_comment_has_no_stack_traces() {
        let text = error_comment(&ctx("/llm review", "review"), "git exited with code 128");
        assert!(!text.contains("panicked"), "{text}");
        assert!(text.contains("job `1a2b3c4d`"), "{text}");
    }
}
